"""Bootstrap helper for the Monday Railway deploy.

What this script does (no Railway access required):

1. Generates a cryptographically-random `<SVC>_SECRET` per service into
   a single file (default ``~/.noesis-secrets``, mode 0600).
2. Prints the eval/.env.e2e block populated with the generated secrets,
   ready to paste in once you know the deployed URLs.
3. Writes a ready-to-edit `.mcp.json` template with placeholders for
   the seven services that aren't yet registered.
4. Emits a copy-paste shell block of `railway variables --set`
   commands that wires `<SVC>_SECRET` + cross-service URLs onto every
   Railway service in one go.

What this script does NOT do:

* Create new Railway services. Railway's CLI doesn't expose a
  ``--dockerfile-path`` flag for new GitHub-source services, so service
  creation still goes through the UI per
  ``docs/operations/deploy-runbook.md`` Phase 2. Once each service
  exists, the rest is automatable.
* Push code. Each Railway service auto-deploys on push to master.
* Touch any environment variable that already has a value (you re-run
  this safely without clobbering rotated secrets — see ``--no-overwrite``).

Pair with ``probe_live_stack.py`` once the deploys are done.

Usage::

    # 1. One-time secret generation
    python tools/deploy_bootstrap.py generate-secrets

    # 2. After Phase 2 of the runbook, with all 8 Railway URLs known:
    python tools/deploy_bootstrap.py emit-railway-cmds \\
        --secrets ~/.noesis-secrets \\
        --logos-url https://noesis-logos.up.railway.app \\
        --mneme-url https://noesis-mneme.up.railway.app \\
        --kairos-url https://noesis-kairos.up.railway.app

    # 3. Update .mcp.json
    python tools/deploy_bootstrap.py emit-mcp-json \\
        --logos-url https://noesis-logos.up.railway.app \\
        ...

    # 4. Print the eval/.env.e2e block
    python tools/deploy_bootstrap.py emit-env-template \\
        --secrets ~/.noesis-secrets \\
        --logos-url https://noesis-logos.up.railway.app \\
        ...
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Services that need a per-service `<SVC>_SECRET` and an MCP entry.
MCP_SERVICES: tuple[str, ...] = (
    "logos",
    "mneme",
    "praxis",
    "telos",
    "episteme",
    "kosmos",
    "empiria",
    "techne",
)

# Services that don't expose tools to Claude but still need a secret +
# Railway service. Kairos is the tracing sink; everyone POSTs spans to it.
INFRA_SERVICES: tuple[str, ...] = ("kairos",)

ALL_SERVICES: tuple[str, ...] = MCP_SERVICES + INFRA_SERVICES


def _hex_token(n_bytes: int = 32) -> str:
    return secrets.token_hex(n_bytes)


def _read_secrets(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text().splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        key, _, value = raw.partition("=")
        key = key.strip()
        value = value.strip().strip("'\"")
        if key:
            out[key] = value
    return out


def _write_secrets(path: Path, secrets_map: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "# Noesis Railway secrets — one per service.\n"
    body += "# Generated by tools/deploy_bootstrap.py.\n"
    body += "# Mode 0600. Treat like a vault. Do NOT commit.\n\n"
    for k in sorted(secrets_map):
        body += f"{k}={secrets_map[k]}\n"
    path.write_text(body)
    try:
        os.chmod(path, 0o600)
    except OSError:
        pass


def cmd_generate_secrets(args: argparse.Namespace) -> int:
    out: Path = args.out
    existing = _read_secrets(out) if not args.fresh else {}
    generated: dict[str, str] = dict(existing)
    new_count = 0
    for svc in ALL_SERVICES:
        key = f"{svc.upper()}_SECRET"
        if key in generated and not args.overwrite:
            continue
        generated[key] = _hex_token()
        new_count += 1
    _write_secrets(out, generated)
    print(f"wrote {out} ({len(generated)} secrets total, {new_count} new)")
    if not args.overwrite and existing:
        print("(use --overwrite to rotate existing keys, --fresh to start over)")
    return 0


def _service_urls_from_args(args: argparse.Namespace) -> dict[str, str]:
    """Pull --<svc>-url flags into a dict, skipping unset ones."""
    urls: dict[str, str] = {}
    for svc in ALL_SERVICES:
        attr = f"{svc}_url"
        url = getattr(args, attr, None)
        if url:
            urls[svc] = url.rstrip("/")
    return urls


def cmd_emit_railway_cmds(args: argparse.Namespace) -> int:
    secrets_map = _read_secrets(args.secrets)
    if not secrets_map:
        print(
            f"ERROR: no secrets read from {args.secrets} — "
            f"run `generate-secrets` first.",
            file=sys.stderr,
        )
        return 2
    urls = _service_urls_from_args(args)
    if not urls:
        print(
            "ERROR: no service URLs provided. Pass --<svc>-url for each.",
            file=sys.stderr,
        )
        return 2

    logos_url = urls.get("logos")
    kairos_url = urls.get("kairos")

    print("# Run these from the repo root after `railway login`.")
    print("# Each `--service` arg refers to a service in the linked")
    print("# Railway project — see `railway service` for names.\n")

    for svc, url in sorted(urls.items()):
        bash_safe = svc.replace("-", "_")
        secret = secrets_map.get(f"{svc.upper()}_SECRET", "")
        if not secret:
            print(f"# WARN: no {svc.upper()}_SECRET in {args.secrets}")
            continue
        sets: list[str] = [f"{svc.upper()}_SECRET={secret}"]
        # Praxis and Mneme call Logos as a sidecar.
        if svc in {"praxis", "mneme"} and logos_url:
            sets.append(f"LOGOS_URL={logos_url}")
            logos_secret = secrets_map.get("LOGOS_SECRET", "")
            if logos_secret:
                sets.append(f"LOGOS_SECRET={logos_secret}")
        # Every service can post traces to Kairos.
        if svc != "kairos" and kairos_url:
            sets.append(f"KAIROS_URL={kairos_url}")
        # Stateful services need the data dir mount.
        if svc in {"mneme", "praxis", "techne"}:
            sets.append(f"{svc.upper()}_DATA_DIR=/data")
        joined = " ".join(f'--set "{kv}"' for kv in sets)
        print(f"# {svc} ({url})")
        print(f"railway variables {joined} --service {bash_safe}")
        print()

    print("# After every variable change, Railway redeploys automatically.")
    print("# Probe the result:")
    print("python tools/probe_live_stack.py")
    return 0


def cmd_emit_mcp_json(args: argparse.Namespace) -> int:
    urls = _service_urls_from_args(args)
    if not urls:
        print(
            "ERROR: no --<svc>-url flags. At minimum pass --logos-url etc.",
            file=sys.stderr,
        )
        return 2
    server_block: dict[str, dict[str, str]] = {}
    for svc in MCP_SERVICES:
        if svc in urls:
            server_block[svc] = {
                "type": "http",
                "url": f"{urls[svc]}/mcp",
            }
    out = {"mcpServers": server_block}
    text = json.dumps(out, indent=2) + "\n"
    if args.write:
        target = REPO_ROOT / ".mcp.json"
        target.write_text(text)
        print(f"wrote {target}")
    else:
        sys.stdout.write(text)
    return 0


def cmd_emit_env_template(args: argparse.Namespace) -> int:
    secrets_map = _read_secrets(args.secrets)
    urls = _service_urls_from_args(args)
    print("# Paste this into eval/.env.e2e (gitignored).")
    print()
    for svc in MCP_SERVICES:
        url = urls.get(svc, f"<https://noesis-{svc}.up.railway.app>")
        secret = secrets_map.get(
            f"{svc.upper()}_SECRET",
            f"<from {args.secrets}: {svc.upper()}_SECRET>",
        )
        print(f"NOESIS_{svc.upper()}_URL={url}")
        print(f"NOESIS_{svc.upper()}_SECRET={secret}")
        print()
    print("NOESIS_AB_MAX_BUDGET_USD=0.25")
    return 0


def _add_url_flags(p: argparse.ArgumentParser) -> None:
    for svc in ALL_SERVICES:
        p.add_argument(
            f"--{svc}-url",
            default=None,
            help=f"Public URL of the {svc} Railway service.",
        )


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n", 1)[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    g = sub.add_parser("generate-secrets", help="Write per-service tokens to a file")
    g.add_argument(
        "--out",
        type=Path,
        default=Path.home() / ".noesis-secrets",
        help="Destination file (default ~/.noesis-secrets, mode 0600).",
    )
    g.add_argument(
        "--overwrite",
        action="store_true",
        help="Rotate existing entries instead of preserving them.",
    )
    g.add_argument(
        "--fresh",
        action="store_true",
        help="Ignore existing file and write from scratch.",
    )
    g.set_defaults(func=cmd_generate_secrets)

    r = sub.add_parser(
        "emit-railway-cmds",
        help="Print `railway variables --set` commands to wire env vars.",
    )
    r.add_argument(
        "--secrets",
        type=Path,
        default=Path.home() / ".noesis-secrets",
        help="Secrets file (default ~/.noesis-secrets).",
    )
    _add_url_flags(r)
    r.set_defaults(func=cmd_emit_railway_cmds)

    m = sub.add_parser(
        "emit-mcp-json",
        help="Print/write a .mcp.json with the deployed URLs.",
    )
    m.add_argument(
        "--write",
        action="store_true",
        help=f"Write the result to {REPO_ROOT}/.mcp.json instead of stdout.",
    )
    _add_url_flags(m)
    m.set_defaults(func=cmd_emit_mcp_json)

    e = sub.add_parser(
        "emit-env-template",
        help="Print eval/.env.e2e block populated with secrets + URLs.",
    )
    e.add_argument(
        "--secrets",
        type=Path,
        default=Path.home() / ".noesis-secrets",
    )
    _add_url_flags(e)
    e.set_defaults(func=cmd_emit_env_template)

    args = p.parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":
    raise SystemExit(main())
