name: empiria

on:
  push:
    branches: [master]
    paths:
      - "services/empiria/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/empiria.yml"
  pull_request:
    paths:
      - "services/empiria/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/empiria.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/empiria
      service-name: empiria
      coverage-args: "--cov=empiria.core"
