name: kosmos

on:
  push:
    branches: [master]
    paths:
      - "services/kosmos/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/kosmos.yml"
  pull_request:
    paths:
      - "services/kosmos/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/kosmos.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/kosmos
      service-name: kosmos
      coverage-args: "--cov=kosmos.core"
      needs-clients: true
