name: mneme

on:
  push:
    branches: [master]
    paths:
      - "services/mneme/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/mneme.yml"
  pull_request:
    paths:
      - "services/mneme/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/mneme.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/mneme
      service-name: mneme
      coverage-args: "--cov=mneme.core"
      needs-clients: true
