name: praxis

on:
  push:
    branches: [master]
    paths:
      - "services/praxis/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/praxis.yml"
  pull_request:
    paths:
      - "services/praxis/**"
      - "schemas/**"
      - "kairos/**"
      - "clients/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/praxis.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/praxis
      service-name: praxis
      coverage-args: "--cov=praxis.core"
      needs-clients: true
