name: techne

on:
  push:
    branches: [master]
    paths:
      - "services/techne/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/techne.yml"
  pull_request:
    paths:
      - "services/techne/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/techne.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/techne
      service-name: techne
      coverage-args: "--cov=techne.core"
