name: telos

on:
  push:
    branches: [master]
    paths:
      - "services/telos/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/telos.yml"
  pull_request:
    paths:
      - "services/telos/**"
      - "schemas/**"
      - "kairos/**"
      - ".github/workflows/_python-component.yml"
      - ".github/workflows/telos.yml"

jobs:
  ci:
    uses: ./.github/workflows/_python-component.yml
    with:
      service-path: services/telos
      service-name: telos
      coverage-args: "--cov=telos.core"
